-- LunaVerse / Nova Language Learning
-- Jalankan seluruh file ini di Supabase SQL Editor.
-- PERINGATAN: bagian RESET menghapus tabel lama beserta seluruh datanya.

begin;

-- ============================================================
-- RESET TABEL LAMA DAN TABEL LUNAVERSE
-- ============================================================

drop table if exists public.bank_soal cascade;
drop table if exists public.materi_bahasa cascade;
drop table if exists public.riwayat_nilai cascade;
drop table if exists public.sertifikat_user cascade;
drop table if exists public.profil_pengguna cascade;
drop table if exists public.quiz_questions cascade;
drop table if exists public.lessons cascade;
drop table if exists public.quiz_attempts cascade;
drop table if exists public.user_streaks cascade;
drop table if exists public.certificates cascade;
drop table if exists public.languages cascade;

-- ============================================================
-- PROFIL DAN ROLE PENGGUNA
-- ============================================================

create table public.profil_pengguna (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  nama text not null default 'Learner',
  role text not null default 'user' check (role in ('admin', 'user')),
  dibuat_pada timestamptz not null default now(),
  diperbarui_pada timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profil_pengguna (id, email, nama, role)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'name', 'Learner'),
    coalesce(new.raw_user_meta_data ->> 'role', 'user')
  )
  on conflict (id) do update set
    email = excluded.email,
    nama = excluded.nama;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

-- Pulihkan profil untuk akun Auth yang sudah ada sebelum schema ini dijalankan.
insert into public.profil_pengguna (id, email, nama, role)
select
  id,
  email,
  coalesce(raw_user_meta_data ->> 'name', 'Learner'),
  coalesce(raw_user_meta_data ->> 'role', 'user')
from auth.users
where email is not null
on conflict (id) do update set
  email = excluded.email,
  nama = excluded.nama;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer set search_path = public
as $$
  select exists (
    select 1 from public.profil_pengguna
    where id = auth.uid() and role = 'admin'
  );
$$;

-- ============================================================
-- BAHASA
-- ============================================================

create table public.languages (
  id text primary key,
  name text not null,
  native_name text not null,
  icon text not null default '🌐',
  lesson_count integer not null default 0 check (lesson_count >= 0),
  created_at timestamptz not null default now()
);

-- ============================================================
-- MATERI
-- ============================================================

create table public.lessons (
  id bigint generated by default as identity primary key,
  language_id text not null references public.languages(id) on delete cascade,
  title text not null,
  summary text not null default '',
  content text not null default '',
  created_at timestamptz not null default now()
);

create index lessons_language_id_idx on public.lessons(language_id);

-- ============================================================
-- BANK SOAL
-- ============================================================

create table public.quiz_questions (
  id bigint generated by default as identity primary key,
  language_id text not null references public.languages(id) on delete cascade,
  question text not null,
  options text[] not null check (cardinality(options) >= 2),
  answer_index integer not null check (answer_index >= 0 and answer_index < cardinality(options)),
  created_at timestamptz not null default now()
);

create index quiz_questions_language_id_idx on public.quiz_questions(language_id);

-- ============================================================
-- HASIL QUIZ
-- ============================================================

create table public.quiz_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  language text not null,
  score integer not null check (score between 0 and 100),
  created_at timestamptz not null default now()
);

create index quiz_attempts_user_id_idx on public.quiz_attempts(user_id);

-- STREAK BELAJAR HARIAN
create table public.user_streaks (
  user_id uuid primary key references auth.users(id) on delete cascade,
  streak_count integer not null default 0 check (streak_count >= 0),
  last_activity_date date,
  updated_at timestamptz not null default now()
);

alter table public.user_streaks enable row level security;
create policy "streak_self_select" on public.user_streaks
for select to authenticated using (user_id = auth.uid());
create policy "streak_self_write" on public.user_streaks
for insert to authenticated with check (user_id = auth.uid());
create policy "streak_self_update" on public.user_streaks
for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

-- ============================================================
-- SERTIFIKAT
-- ============================================================

create table public.certificates (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  issued_at timestamptz not null default now()
);

create index certificates_user_id_idx on public.certificates(user_id);

-- ============================================================
-- DATA AWAL LIMA BAHASA
-- ============================================================

insert into public.languages (id, name, native_name, icon, lesson_count)
values
  ('en', 'English', 'English', '🇬🇧', 2),
  ('ja', 'Japanese', '日本語', '🇯🇵', 2),
  ('es', 'Spanish', 'Español', '🇪🇸', 2),
  ('zh', 'Chinese', '中文', '🇨🇳', 2),
  ('ko', 'Korean', '한국어', '🇰🇷', 2);

insert into public.lessons (language_id, title, summary, content)
values
  ('en', 'First Steps', 'Sapaan dan frasa dasar bahasa Inggris.', 'Pelajari Hello, Good morning, How are you?, Thank you, dan See you later.'),
  ('en', 'Daily Phrases', 'Kosakata yang digunakan sehari-hari.', 'Gunakan frasa praktis untuk percakapan singkat sehari-hari.'),
  ('ja', 'Hajimemashite', 'Perkenalan dasar bahasa Jepang.', 'Pelajari Ohayou, Konnichiwa, Konbanwa, dan Hajimemashite.'),
  ('ja', 'Daily Japanese', 'Frasa praktis bahasa Jepang.', 'Latih frasa sederhana untuk aktivitas sehari-hari.'),
  ('es', 'Hola Spanish', 'Sapaan dasar bahasa Spanyol.', 'Pelajari Hola, Buenos dias, Gracias, dan Hasta luego.'),
  ('es', 'Everyday Spanish', 'Frasa percakapan sehari-hari.', 'Gunakan frasa pendek untuk memperkenalkan diri dan bertanya.'),
  ('zh', 'Ni Hao Chinese', 'Sapaan dasar bahasa Mandarin.', 'Pelajari Ni hao, Zaijian, Xiexie, dan Qing.'),
  ('zh', 'Everyday Chinese', 'Frasa praktis bahasa Mandarin.', 'Latih kosakata sederhana untuk percakapan harian.'),
  ('ko', 'Annyeong Korean', 'Sapaan dasar bahasa Korea.', 'Pelajari Annyeonghaseyo, Gamsahamnida, dan Jal jinaeyo.'),
  ('ko', 'Everyday Korean', 'Frasa percakapan bahasa Korea.', 'Gunakan frasa pendek untuk situasi sehari-hari.');

insert into public.quiz_questions (language_id, question, options, answer_index)
values
  ('en', 'What does hello mean?', array['Halo', 'Selamat tinggal', 'Terima kasih'], 0),
  ('en', 'Choose the correct sentence.', array['I am learn.', 'I am learning.', 'I learning am.'], 1),
  ('ja', 'What does Konnichiwa mean?', array['Selamat pagi', 'Halo', 'Terima kasih'], 1),
  ('es', 'What does Gracias mean?', array['Halo', 'Terima kasih', 'Sampai jumpa'], 1),
  ('zh', 'What does Ni hao mean?', array['Halo', 'Maaf', 'Selamat malam'], 0),
  ('ko', 'What does Gamsahamnida mean?', array['Permisi', 'Terima kasih', 'Sampai jumpa'], 1);

-- ============================================================
-- RLS DAN POLICY
-- ============================================================

alter table public.profil_pengguna enable row level security;
alter table public.languages enable row level security;
alter table public.lessons enable row level security;
alter table public.quiz_questions enable row level security;
alter table public.quiz_attempts enable row level security;
alter table public.certificates enable row level security;

create policy "profile_self_select" on public.profil_pengguna
for select to authenticated using (id = auth.uid() or public.is_admin());

create policy "profile_admin_write" on public.profil_pengguna
for all to authenticated using (public.is_admin()) with check (public.is_admin());

create policy "languages_authenticated_select" on public.languages
for select to authenticated using (true);

create policy "languages_admin_write" on public.languages
for all to authenticated using (public.is_admin()) with check (public.is_admin());

create policy "lessons_authenticated_select" on public.lessons
for select to authenticated using (true);

create policy "lessons_admin_write" on public.lessons
for all to authenticated using (public.is_admin()) with check (public.is_admin());

create policy "questions_authenticated_select" on public.quiz_questions
for select to authenticated using (true);

create policy "questions_admin_write" on public.quiz_questions
for all to authenticated using (public.is_admin()) with check (public.is_admin());

create policy "attempts_self_select" on public.quiz_attempts
for select to authenticated using (user_id = auth.uid() or public.is_admin());

create policy "attempts_self_insert" on public.quiz_attempts
for insert to authenticated with check (user_id = auth.uid());

create policy "attempts_admin_write" on public.quiz_attempts
for update to authenticated using (public.is_admin()) with check (public.is_admin());

create policy "attempts_admin_delete" on public.quiz_attempts
for delete to authenticated using (public.is_admin());

create policy "certificates_self_select" on public.certificates
for select to authenticated using (user_id = auth.uid() or public.is_admin());

create policy "certificates_admin_write" on public.certificates
for all to authenticated using (public.is_admin()) with check (public.is_admin());

commit;

-- Setelah membuat akun admin di Authentication > Users, jalankan:
-- update public.profil_pengguna
-- set role = 'admin', nama = 'Luna Admin'
-- where email = 'email-admin-anda@example.com';
